export const Posts = [
  {
    id: 1,
    desc: "I am so happy that we are together.",
    userName: "Serkan Demir",
    photo: "assets/post/ogretmen.jpg",
    profilePhoto: "assets/serkan.png",
    date: "5 mins ago",
    userId: 1,
    like: 653.234,
    comment: 55.465,
  },
  {
    id: 2,
    userName: "Erkan Güneş",
    desc: "Enjoying a nice picnic in nature.",
    photo: "assets/post/seko.jpg",
    profilePhoto: "assets/erkan.png",
    date: "15 mins ago",
    userId: 2,
    like: 453.539,
    comment: 123.564,
  },

  {
    id: 4,
    userName: "Murat Aygün",
    desc: " Because there is an unbreakable friendship between them.",
    photo: "assets/post/karsıyaka.jpg",
    profilePhoto: "assets/person/9.jpeg.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 953.132,
    comment: 3,
  },
  {
    id: 3,
    userName: "Burak Solmaz",
    desc: "We tasted Turkish Kebab in Gaziantep.",
    photo: "assets/post/burak.jpg",
    profilePhoto: "assets/post/fener.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 553.435,
    comment: 2,
  },
  {
    id: 5,
    userName: "Blander",
    desc: "I don't know if it's the biggest but it's very big.",
    photo: "assets/person/8.jpeg.jpeg",
    profilePhoto: "assets/person/10.jpeg.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 853.436,
    comment: 5,
  },
  {
    id: 6,
    userName: "Hadise",
    desc: "I'm always happy.",
    photo: "assets/person/7.jpeg.jpeg",
    profilePhoto: "assets/post/3.jpeg.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 153.244,
    comment: 6,
  },
  {
    id: 7,
    userName: "Beyza",
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/3.jpeg.jpeg",
    profilePhoto: "assets/person/4.jpeg.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 553.224,
    comment: 3,
  },
  {
    id: 8,
    userName: "Fatma",
    photo: "assets/post/4.jpeg.jpeg",
    profilePhoto: "assets/person/6.jpeg.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 653.215,
    comment: 1,
  },
];
